require_relative 'databases/database.rb'
require_relative 'entities/user.rb'
require_relative 'entities/match.rb'
require_relative 'scripts/user_sign_in.rb'
require_relative 'scripts/user_sign_up.rb'
require_relative 'scripts/new_match.rb'
require_relative 'scripts/continue_match.rb'
require_relative 'scripts/turn.rb'